Name:           ros-melodic-cloudwatch-logger
Version:        2.0.0
Release:        1%{?dist}
Summary:        ROS cloudwatch_logger package

Group:          Development/Libraries
License:        Apache 2.0
URL:            http://wiki.ros.org/cloudwatch_logger
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-aws-common
Requires:       ros-melodic-aws-ros1-common
Requires:       ros-melodic-cloudwatch-logs-common
Requires:       ros-melodic-roscpp
BuildRequires:  ros-melodic-aws-common
BuildRequires:  ros-melodic-aws-ros1-common
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-cloudwatch-logs-common
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-rostest

%description
CloudWatch Logger node for publishing logs to AWS CloudWatch Logs

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Fri Mar 22 2019 AWS RoboMaker <ros-contributions@amazon.com> - 2.0.0-1
- Autogenerated by Bloom

